config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'about' => 'welcome#about'

  get 'services' => 'welcome#services'

  get 'our_caregivers' => 'welcome#our_caregivers'

  get 'employment_opportunities' => 'welcome#employment_opportunities'

  get 'resources' => 'welcome#resources'

  get 'contact_us' => 'welcome#contact_us'

  get 'apply_today' => 'welcome#apply_today'

  get 'testimonials' => 'welcome#testimonials'

  get 'fall_prevention_program' => 'welcome#fall_prevention_program'

  get 'professional_affiliations' => 'welcome#professional_affiliations'

  get 'request_an_assessment' => 'welcome#request_an_assessment'

  get 'respite_care' => 'welcome#respite_care'

  get 'welcome_home_package' => 'welcome#welcome_home_package'

  get 'why_home_care' => 'welcome#why_home_care'

  root 'welcome#home'

  resources :events

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :event_list

  def event_list
  	@events = Event.all.order(:date)
  	@event_show = []
  	@events.each do |event|
  		if event.date >= Date.today
  			@event_show.push(event)
  		end
  	end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!

  # GET /events
  # GET /events.json
  def index
    @events = Event.all.order(:date)
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :info, :date)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    @events = Event.all.order(:date)
  end

  def about
  end

  def services
  end

  def our_caregivers
  end

  def employment_opportunities
  end

  def resources
  end

  def contact_us
  end

  def apply_today
  end

  def fall_prevention_program
  end

  def professional_affiliations
  end

  def request_an_assessment
  end

  def respite_care
  end

  def testimonials
  end

  def welcome_home_package
  end

  def why_home_care
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
  <h1>Listing events</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Info</th>
        <th>Date</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= event.title %></td>
          <td><%= event.info %></td>
          <td><%= event.date %></td>
          <td><%= link_to 'Show', event %></td>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Info:</strong>
  <%= @event.info %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>In-Home Care and Assisted Living in Cobb, Metro Atlanta, Cherokee, Fulton, Paulding | Caregivers and Senior Care in Dekalb County | Comforting Arms CALL NOW: 678-819-3775</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
</head>

<body>

  <div class="jumbotron">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-3 jtcontent">
          <%= image_tag ("jtlogo.png") %> 
          <div class="jtcontent">
            <h3>Call us at <%= link_to "678-819-3775", "tel:678-819-3775", class: "no-link-dec" %></h3>
          </div>
        </div>
      </div>
    </div>
  </div>

  <nav class="navbar navbar-default navbar-static-top" role="navigation" id="topnavbar" data-spy="affix" data-offset-top="310">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%=link_to image_tag("heart.png", :border => 0), root_path, :class => 'navbar-brand brand_logo'%>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="dropdown <% if @page == "about" %>
                                <%= "active" %>
                              <% end %>">
            <%= link_to about_path, class: "dropdown-toggle no-link-dec" do %>
              About
              <span class="caret"></span>
            <% end %>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'About Us', about_path, class: "no-link-dec" %></li>
              <li class="divider"></li>
              <li><%= link_to 'Testimonials', testimonials_path, class: "no-link-dec" %></li>
            </ul>
          </li>
          <li class="dropdown <% if @page == "services" %>
                                <%= "active" %>
                              <% end %>">
            <%= link_to services_path, class: "dropdown-toggle no-link-dec" do %>
              Services
              <span class="caret"></span>
            <% end %>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Services', services_path, class: "no-link-dec" %></li>
              <li class="divider"></li>
              <li><%= link_to 'Welcome Home Package', welcome_home_package_path, class: "no-link-dec" %></li>
              <li class="divider"></li>
              <li><%= link_to 'Why Home Care?', why_home_care_path, class: "no-link-dec" %></li>
              <li class="divider"></li>
              <li><%= link_to 'Respite Care', respite_care_path, class: "no-link-dec" %></li>
              <li class="divider"></li>
              <li><%= link_to 'Request an Assessment', request_an_assessment_path, class: "no-link-dec" %></li>
            </ul>
          </li>
          <li class="<%= 'active' if @page == "caregivers" %>"><%= link_to 'Our Caregivers', our_caregivers_path, class: "no-link-dec" %></li>
          <li class="dropdown <% if @page == "employment" %>
                                <%= "active" %>
                              <% end %>">
            <%= link_to employment_opportunities_path, class: "dropdown-toggle no-link-dec" do %>
              Employment Opportunitites
              <span class="caret"></span>
            <% end %>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Employment Opportunities', employment_opportunities_path, class: "no-link-dec" %></li>
              <li class="divider"></li>
              <li><%= link_to 'Apply Today', apply_today_path, class: "no-link-dec" %></li>
            </ul>
          </li>
          <li class="dropdown <% if @page == "resources" %>
                                <%= "active" %>
                              <% end %>">
            <%= link_to resources_path, class: "dropdown-toggle no-link-dec" do %>
              Resources
              <span class="caret"></span>
            <% end %>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Resources', resources_path, class: "no-link-dec" %></li>
              <li class="divider"></li>
              <li><%= link_to 'Fall Prevention Program', fall_prevention_program_path, class: "no-link-dec" %></li>
              <li class="divider"></li>
              <li><%= link_to 'Professional Affiliations', professional_affiliations_path, class: "no-link-dec" %></li>
            </ul>
          </li>
          <li class="<%= 'active' if @page == "contact" %>"><%= link_to 'Contact Us', contact_us_path, class: "no-link-dec" %></li>
        </ul>
        
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="container">
    <div class="row">
      <div class="col-md-3 side-bar">
        <div class="panel panel-primary">
          <div class="panel-heading">
            DOWNLOAD OUR BROCHURE
          </div>
          <div class="panel-body">
            <ul>
              <li><%= link_to "Comforting Arms Brochure", "http://comfortingarms.com/wp-content/uploads/Comforting-Arms-Brochure-v2.pdf", target: "_blank" %></li>
            </ul>
          </div>
        </div>
        <div class="panel panel-primary">
          <div class="panel-heading">
            Upcoming Events
          </div>
          <div class="panel-body">
            <% if @events.empty? != true %>
              <ul class="event-box">
                <% @events.each do |event| %>
                  <li> 
                    <div class="panel panel-default">
                      <div class="panel-heading">
                        <strong><%= event.title %></strong>
                      </div>
                      <div class="panel-body">
                        <p><%= event.info %></p>
                        <p><strong><%= event.date.strftime("%A, %B %e, %Y ") %></strong></p>
                      </div>
                    </div>
                  </li>
                <% end %>
              </ul>
            <% else %>
              <p>There are no upcoming events at this time. Please check back later</p>  
            <% end %>
          </div>
        </div>
        <div class="panel panel-primary">
          <div class="panel-heading">
            Follow Us
          </div>
          <div class="panel-body">
            <div class="container">
              <span class="invisible">Blanks</span>
              <%= link_to(image_tag("facebook.png"), "https://www.facebook.com/comfortingarms", target: "_blank") %>
              <%= link_to(image_tag("twitter.png"), "https://twitter.com/ComfortingArmsG", target: "_blank") %>
              <%= link_to(image_tag("linkedin.png"), "https://www.linkedin.com/company/comforting-arms", target: "_blank") %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-8">
        <div class="content">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>

</body>
</html>

app/views/welcome/employment_opportunities.html.erb
<% @page = "employment" %>
<h3>Employment Opportunities</h3>
<br />
<p><strong>A Rewarding Career Helping Seniors and Their Families</strong></p> 
<br />
<p>Work in one of the most rewarding positions in your community! We are actively seeking caring individuals who would like to make a difference in their area by working as caregivers for the elderly. We provide what is known as “companion care” for seniors so they can remain independent in their own homes for as long as possible. We assist the elderly with meal planning and preparation, errands and incidental transportation, laundry, light housekeeping, and many other needed tasks.</p>
<%= image_tag "employment.jpg", class: "caregivers-img" %>
<br />
<p><strong>Our Hiring Process</strong></p>
<br />
<p>We are seeking caregivers who are warm, compassionate and love working with the elderly. You must be caring and patient. The hours are flexible and can be part-time or full-time. You do not need to be experienced or licensed. We supply the training. We will only hire individuals who can pass criminal and motor vehicle background checks with stellar marks. You need to have a valid Driver’s License, a clean driving record, a reliable car with up-to-date insurance, and compassion and love for seniors. We cannot hire you if have a criminal record, a recent history of drug or alcohol abuse, or carry a communicable disease such as tuberculosis. Prior to hiring caregivers, we require health certificates and we run thorough background checks.</p>
<br />
<p><strong>Our Training</strong></p>
<br />
<p>We are committed to providing our clients with the most professional caregivers in the area. In order to ensure this, we look for warm, honest, caring people, and then we help them to gain the education necessary to become the best around. Our caregivers have the opportunity to become Certified Companion Aides, CCA’s®, a designation that elevates their knowledge and status in the industry.</p>
<br />
<p>Those who complete the <%= link_to "Certified Companion Aide (CCA®)", "http://www.theseniorschoice.com/mm/CCA.html" %> program have successfully completed an exclusive training program specially designed for companion caregivers. This program, derived from a popular certified nursing assistant program, is a compilation of the best standards and practices available in companion care, focusing on 19 essential care subjects, including:</p>
<br />
<ul>
	<li>Professionalism</li>
	<li>Understanding Aging</li>
	<li>Safe and Comfortable Transfers</li>
	<li>Chronic Medical Conditions</li>
	<li>Infection Control</li>
	<li>Maintaining Safe and Healthy Home Environments</li>
	<li>Nutritional Needs</li>
	<li>Meal Planning and Preparation</li>
	<li>And much more!</li>
</ul>
<br />
<p>No other companion care company offers such a comprehensive training program. Clients can trust that our CCA’s ® will perform their duties with professionalism and dedication while they help our clients maintain their independence and treat them and their loved ones with the dignity and respect that they deserve. Our CCA’s ® represent some of the finest caregivers in the industry.</p>
<br />
<p><strong>Here’s what some of our caregivers are saying about our Certified Companion Aide (CCA®) program:</strong></p>
<br />
<em><p>“I just wanted to take a moment to thank you for such a great learning tool, the Certified Companion Aid (CCA) Program. I was a CNA working for several nursing homes, but this program is so comprehensive I can’t compare it to the certification program for nursing assistants. The program provides a more detailed description of what senior care is really about. The chapters look at the senior as a whole person. The program also presents detailed information and diagrams every CNA or home healthcare professional should have. The CCA program guarantees each senior has the best care available. Thank you again.”</p>
<br />
<p>“I did not have a lot of formal [education] as a caregiver and the CCA program helped me to gain a better knowledge of what to expect as a caregiver and how to deal with certain situations. The instructional material was interesting and I think that it has given me more confidence as a caregiver.”</p>
<br />
<p>“The CCA program has taught me to be a more well-rounded caregiver. Instead of just being proficient at meeting the clients’ physical needs, I now feel more prepared to meet their nutritional, social, emotional and spiritual needs, as well.”</p></em>
<br />
<p>Thank you for your interest in working with us to make life better for seniors and their families. We look forward to being able to discuss employment opportunities with you, and to advance your training, skills and career. You can start the process of becoming a caregiver with Comforting Arms by <%= link_to "submitting an application", apply_today_path %>.</p>

app/views/welcome/fall_prevention_program.html.erb
<% @page = "resources" %>
<h3>Fall Prevention Program</h3>
<%= image_tag "fall_prevention.jpg", class: "fall-prevent-img" %>
<br />
<p><strong>Request a Free Fall Prevention Workshop for Your Group!</strong></p>
<br />
<p>Comforting Arms is proud to be the Cobb, Cherokee, Dekalb, Fulton and Paulding county’s “resident experts” in fall prevention. Let us share some ideas with your family, friends, company, organization, or group about how to prevent one of the most catastrophic events in the life of a senior citizen.</p>
<br />
<p><strong>Did you know that:</strong></p>
<ul>
	<li>70% of accidental deaths in people over the age of 75 result from falls?</li>
	<li>We spend $79 billion in medical costs each year on accidents attributable to falls?</li>
	<li>40% of all nursing home admissions are attributable to repeated falls at home?</li>
	<li>1 out of every 3 seniors who lives independently in their homes will seek medical care for a major fall each year?  If you are over 75, the likelihood of falling is even greater.</li>
	<li>25% of seniors who suffer hip fractures die within one year?
	Survivors of falls may experience debilitating fractures of the hip, wrists or spine?</li>
	<li>Falling, or the fear of falling, often times leads to loss of confidence, imposed isolation and immobility?</li>
</ul>
<br />
<p>As you can see, the consequences of falling are very serious to seniors and their families. We are very concerned about the effects that falls have on seniors. We routinely speak to groups, both large and small, about how to prevent falls. We have developed a dynamic presentation (ranging from 20 to 60 minutes in length) that we would love to share with your group.  In this presentation, we share such things as:</p>
<ul>
	<li>The frequency and effects of falls among seniors</li>
	<li>The most common causes of falls</li>
	<li>Things you can do to reduce the risk of falling</li>
	<li>What to do when someone falls</li>
	<li>How to tell if you or someone you love is at risk of a fall</li>
</ul>
<br />
<p>With each presentation, brochures, videos and other materials are available for each person. In addition, each senior will have the opportunity to participate in a free risk assessment. If you would like us to present this valuable program at your group’s next meeting, simply <%= link_to "contact us", contact_us_path %>.</p>

app/views/welcome/our_caregivers.html.erb
<% @page = "caregivers" %>
<h3>Our Caregivers</h3>
<br />
<%= image_tag "caregivers.jpg", class: "caregivers-img" %>
<p>Comforting Arms is devoted to providing the most professional, reliable and friendly caregivers in the industry. Our caregivers provide assistance with such activities as errands, transportation to doctors, medication reminders, housekeeping, laundry, grooming, dressing, bath safety monitoring, and more. All services and schedules are tailored to the needs of the client, and our caregivers are available for hourly, daily, weekly, overnight, 24-hour or live-in assignments. Our wonderful aides truly have a passion for providing care – and they are OUR employees, thoroughly interviewed, screened and background-checked (state and national), trained and oriented, bonded and insured. We have rigorous hiring practices in which all applicants go through tests and screenings focusing on skills, experience, attitudes and placement into homes. Most importantly, each and every one of our caregivers must be dependable, warm and caring people.  Many of our staff members have extensive experience caring for Alzheimer’s and dementia patients.</p>
<br />
<p>Our caregivers are the cream of the crop. They are totally committed, highly qualified and carefully selected individuals who are dependable and extraordinarily caring of others.  In order to ensure this, we look for warm, honest, caring people and then we help them boost their skills to become the best the industry has to offer. Our caregivers have access to our exclusive <%= link_to "Certified Companion Aide (CCA®)", "http://www.theseniorschoice.com/mm/CCA.html", target: "_blank" %> and <%= link_to "Certified Hospice Companion Aide (CHCA®)", "http://www.theseniorschoice.com/mm/CHCA.html", target: "_blank" %> programs. The CCA® designation elevates their knowledge and status in the industry and instills in them the highest standards of caregiver professionalism. The CHCA® specialized training program was designed by a hospice nurse and educates caregivers on death and dying, how to assist patients and hospice nurses with end of life care and prepares them for the emotional consequences of caring for the terminally ill. So, in addition to their previous experience, our caregivers receive continuous training through this one-of-a-kind curriculum, guaranteeing that Comforting Arms’ caregivers remain the bar-setting home care professionals in our community.</p>
<br />
<p>No other in-home care company in our area offers such comprehensive training programs. Clients can trust our CCA’s and CHCA’s to perform their duties with professionalism and dedication while they help clients maintain independence and treat them and their loved ones with the dignity and respect that they deserve.</p>
<br />
<p style="text-align: center"><strong>Comforting Arms Employee Vickie Bonney Wins Prestigious National Award:<br />The Senior’s Choice “Caregiver of the Season”</strong></p>

<p>Kennesaw, Ga – February 27, 2014 – Acworth resident Vickie Bonney, a professional caregiver and Certified Nursing Assistant with Comforting Arms, has won the prestigious “Caregiver of the Season” Award, bestowed by the world’s largest membership network of senior care providers, The Senior’s Choice. The award recognizes “dedicated service to seniors” and “caregivers who perform in an exemplary manner and whose efforts help seniors live the dignified, meaningful and socially connected lives they deserve”.</p>

<p>The owners and senior staff at Comforting Arms see Vickie as the picture of a perfect caregiver. She is dependable, attentive, observant, embodies strong leadership skills, and is always willing to go the extra mile to provide the highest caliber of service to her client(s). Vickie provides the kind of “client/caregiver partnership” that is considered ideal in the in-home senior care field. She also values her own continuing education and improvement, completing the Certified Companion Aid course since joining Comforting Arms and plans to complete the Certified Hospice Companion Aide course in the near future.</p>

<p>Phil Graiser, owner of Comforting Arms, summed it up: “Vickie is the embodiment of the ideal caregiver. As she expressed in her initial interview with us, she genuinely loves caring for others, and this love is clear in the way that she treats her client and performs her assignments. We are so proud of her!”</p>

<p>Steve Everhart, President and CEO of The Senior’s Choice, expressed his admiration of Comforting Arms founders, Phil and Julie Graiser. “It is your leadership that inspires your caregivers to be the exceptional people they are, “said Everhart.</p>

 

<p>Does your loved one deserve this level of superior care? Of course they do. Bring us in for a <%= link_to "no-obligation assessment", request_an_assessment_path %> today.</p>

app/views/welcome/request_an_assessment.html.erb
<% @page = "services" %>
<h3>Request an Assessment</h3>
<br />
<%= image_tag ("raaimg.jpg"), class: "whc-img" %>
<p>Before beginning services, we need to know more about you. We begin with a complimentary assessment to determine your care needs. We start the process by conducting an in-depth assessment of you or your loved one’s lifestyle, medical conditions and the kind of assistance needed that will help them to remain independent at home. We will meet with you and your family and jointly determine the scope of care.</p>
<br />
<p>During the meeting, we explain fully the services available, answer any additional questions, and help with the important care decisions faced by the family with a loved one in need.</p>
<br />
<p><strong>Issues covered include the following:</strong></p>
<br />
<ul>
	<li>Matching the appropriate caregiver</li>
	<li>Daily routines</li>
	<li>Health and medication issues</li>
	<li>Emergency response</li>
	<li>Nutritional issues</li>
	<li>Home cleaning issues</li>
	<li>Transportation needs</li>
	<li>Costs of services</li>
</ul>
<br />
<p>After meeting with the senior or family, a customized and comprehensive Care Plan is developed to meet the physical, psychological and social needs of the senior and the family.</p>
<br />
<p>We take a holistic approach to matching the best caregiver with your loved one, taking into account such important elements as the senior’s needs and personality. Moreover, ongoing follow-up supervision ensures that the care plan is well-implemented and that the senior’s changing needs are met with diligence. We are always mindful of family finances, and we can create a care plan that meets almost anyone’s budget.</p>
<br />
<p>So don’t delay – take advantage of this no-obligation opportunity to assess your needs and discover how we can significantly improve your life and the life of your loved one. For more information, or to request a FREE assessment meeting, simply <%= link_to 'contact us', contact_us_path %> at <%= link_to "678-819-3775", "tel:678-819-3775", class: "no-link-dec" %> or <%= link_to "info@comfortingarms.com", "mailto:info@comfortingarms.com" %>.</p>

app/views/welcome/services.html.erb
<% @page = "services" %>
<h3>Senior Care Services</h3>
<%= image_tag ("services.jpg"), class: "services-img" %>
<p>Comforting Arms is the perfect solution for seniors and others in need who aren’t ready to leave their home for an institutional setting, but because of illness or chronic conditions need support to remain at home. We improve your life by providing compassionate, one-on-one care in the comfort of your own home. Our personalized and affordable services are available 7 days a week and can range from a few hours a day to 24/7 live-in care.</p>

<br />

<p>Comforting Arms provides service in private homes, assisted living communities, hospitals, skilled nursing facilities, and rehabilitation centers. Our highly-qualified and trained caregivers are ready to help you and your loved ones with a variety of daily activities, such as:</p>

<br />

<div class="row">
	<div class="col-md-6">
		<ul>
			<li><em>Light Housekeeping</em></li>
				<ul>
					<li>Dust</li>
					<li>Vacuum</li>
					<li>Clean kitchen</li>
					<li>Organize closets</li>
					<li>Change the linen</li>
					<li>Light laundry</li>
					<li>Light ironing</li>
				</ul>

			<li><em>Miscellaneous</em></li>
				<ul>
					<li>Stay awake overnight</li>
					<li>Prepare breakfast</li>
					<li>Companionship</li>
					<li>Conversation</li>
					<li>Read together</li>
					<li>Games and puzzles</li>
					<li>Arts and Crafts</li>
					<li>Cook together</li>
					<li>Watch TV</li>
					<li>Pet Care</li>
					<li>Mend clothes</li>
					<li>Answer the phone</li>
					<li>Read mail</li>
				</ul>
		</ul>
	</div>
	<div class="col-md-6">
		<ul>
			<li><em>Light Personal Care</em></em></li>
				<ul>
					<li>Medication reminders</li>
					<li>Monitor bathing</li>
					<li>Grooming monitoring</li>
					<li>Dressing monitoring</li>
					<li>Transfers</li>
				</ul>

			<li><em>Sleep-Over Services</em></li>
				<ul>
					<li>Stay awake overnight</li>
					<li>Prepare breakfast</li>
				</ul>

			<li><em>Errands & Transportation</em></li>
				<ul>
					<li>Organize closets</li>
					<li>Change the linen</li>
					<li>Groceries and shopping</li>
					<li>Pick up prescriptions</li>
					<li>Movie events</li>
					<li>Dine out for meals</li>
					<li>Drive to family</li>
					<li>Handle dry cleaning</li>
					<li>Stamps, mail packages</li>
					<li>Attend church services</li>
					<li>Home Maintenance</li>
				</ul>
		</ul>
	</div>
</div>

<br />

<p><em>Extended Services:</em></p>

<p>This level of service includes more extensive assistance with personal senior care. Services may include all of the above listed activities and:</p>
<br />
<ul>
	<li>Bathing assistance</li>
	<li>Grooming assistance</li>
	<li>Dressing assistance</li>
	<li>Extensive transfers</li>
	<li>Live-in assistance</li>
</ul>
<br />

<p>We know that every client is unique, and our in-depth assessment process allows us to custom tailor our services to meet your specific needs. <%= link_to 'Click Here', request_an_assessment_path %> to learn more about our assessment process or to schedule a complimentary in-home assessment.</p>